#!/usr/bin/python3
import sys

def factorize_numbers(filename):
    """
    Function to factorize numbers from a file into a product of two smaller numbers
    """
    try:
        with open(filename) as f:
            for line in f:
                number = int(line.strip())
                factor1 = 2
                while number % factor1 != 0:
                    factor1 += 1
                factor2 = number // factor1
                print(f"{number}={factor2}*{factor1}")
    except FileNotFoundError:
        print("File not found.")
    except ValueError:
        print("Invalid input in the file.")
    except Exception as e:
        print(f"An error occurred: {e}")

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: ./factors <file>")
    else:
        filename = sys.argv[1]
        factorize_numbers(filename)

